### ISSUE TITLE
Oubli des préfixes dans les boucles foreach

### ISSUE THREAD

**Issue by hbaltz** [Rudymil/ProjetPersonnel2#1]
Dans tes foreach tu ne précises par les préfixes des entités aux quelles tu souhaites accéder:

Par exemple pour les personnes tu as écris:
<xsl:for-each select="Personne">

Il faut mettre:
<xsl:for-each select="tsi2016:tsi2016/tsi2016:Personne">
Pour que la boucle fonctionne

**Comment by Rudymil** [comment]
Merci pour ta réponse.

J'étais parti sur cette idée au début. Mais ça me donne le même résultat.

Pourquoi je n'arrive pas à rentrer dans mon arborescence ? Je souhaite parcourir toutes les entités "Personne" puis les entités "Employeur"...

**Comment by Rudymil** [comment]
Ca y est j'ai réussi à me débloquer... Ton idée est bonne, en fait c'est le transformateur Notepad++ qui ne fonctionne pas !

Merci beaucoup.
